"""seed companies

Revision ID: 7b96ae5e2b85
Revises: 060b8d2a6cf3
Create Date: 2026-06-19 14:42:12.381433

"""
import json
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b96ae5e2b85'
down_revision: Union[str, Sequence[str], None] = '060b8d2a6cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Seeding companies"""
    json_path = Path(__file__).parents[2] / \
        "app" / "companies" / "companies.json"
    with open(json_path) as f:
        companies = json.load(f)
        # Build rows matching your Company model columns
        rows = [{
            "cik": str(c["cik_str"]),
            "ticker": c["ticker"],
            "title": c["title"]
        }
            for c in companies
        ]
        # Bulk insert
        op.bulk_insert(
            sa.table(
                "companies",
                sa.Column("cik", sa.String(20)),
                sa.Column("ticker", sa.String(10)),
                sa.Column("title", sa.String(255)),
            ),
            rows,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
