"""generate insiders, filings and transactions table

Revision ID: 84142c5d5d59
Revises: 7b96ae5e2b85
Create Date: 2026-06-27 16:26:21.736793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84142c5d5d59'
down_revision: Union[str, Sequence[str], None] = '7b96ae5e2b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insiders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filings',
    sa.Column('accession_no', sa.String(length=30), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('insider_id', sa.Integer(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('filing_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('accession_no')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.String(length=30), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.accession_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('filings')
    op.drop_table('insiders')
    # ### end Alembic commands ###
